### ISSUE TITLE
[Release Milestone Checklist] v3.0.0 TODO

### ISSUE THREAD

**Issue by DuckBoss** [DuckBoss/JJMumbleBot#140]
Remaining items until v3.0.0 release:
- [x] Port youtube plugin to v3.0.0
- [ ] Finish quick setup utility for v3.0.0
- [ ] Finish CLA system for v3.0.0
- [ ] Update unit test system for v3.0.0
- [ ] Include a PDF manual with each release
- [ ] Rework web interface for v3.0.0 architecture
- [ ] Fix TTS : !tts 'message' command
- [ ] Create aliases template to generate aliases.csv during quick setup process
- [ ] Create user privileges template to generate user_privileges.csv during quick setup process

**Comment by DuckBoss** [comment]
Moved to PR
