### ISSUE TITLE
v4.0 Release Checklist

### ISSUE THREAD

**Issue by DuckBoss** [DuckBoss/JJMumbleBot#244]
### The changes shown below are already in the master branch and v4.0.0 testing branch, check it out early if you want!

A list of remaining tasks I want to complete for the v4.0 release.

- [x] Make third-party plugin developers lives a lot easier by making it easy to make plugins in v4.0.0
- [x] Add optional proxy url support for media plugin for users that use proxy servers.
- [x] Add optional cookies file support for media plugin for users that may hit rate-limits. 
- [x] Add optional auto-reconnect on bot disconnection.
- [x] Fix youtube clip downloading and ffmpeg post processing issues (Reference: #238).
- [x] Update wiki/documentation for v4.0.0 release.
- [x] Add `!pause/!resume` commands to the audio interface system (Reference: #227).
- [x] Update web interface to display media queue and support direct audio controls from the interface.
- [x] (Security) Remove server connection settings from config.ini, move to command-line arguments so server ip/port/pass is not stored in files.
- [x] Update QSU web pages due to changes in config files
- [x] Improve channels/users display in the web interface (doesn't look that great right now)

Bugs to fix:
- [x] Fix vlc instance not progressing to the next track after finished playing even though the audio interface processes the change.
- [x] Fix audio ducking no longer working with recent commits (most likely something in the web interface)
- [x] Fix !sbrandom/!sbrandomnow commands in the sound board plugin.
- [x] Fix Travis CI tests.
- [x] Fix background color not being set correctly in PGUI. 
- [x] Fix !setalias command not working for multi-command aliases.

**I'll list out some (not all) major features/changes in v4.0.0 below:**
> - Updated Web Interface
        - A fully functional media player is available in the web interface to control the bot audio.
> - Reworked Commands/Aliases Processing System
        - New alias processing so that aliases work regardless of what command token you use (ex: !echo/~echo/$echo)
        - New callback-based command processing in plugins which make adding new commands super easy.
> - Centralized audio controls for whatever plugin is using the audio interface.
        - `!volume/!pause/!resume/!replay/!shuffle/!skip/!stop/!loop/etc etc....` are commands for the audio interface that will work across any audio plugin (no more separate commands for each plugin, like !sbstop or !ytstop, etc.)
        - Improved "Do Not Interrupt" system so audio plugins don't accidentally play over each other
        - Improved track looping system (no longer interrupts audio/queue)
        - Implemented callback system so audio plugins can react to events in the audio interface.
        - Any audio plugin (third-party or not) can easily use this audio interface to make plugin development fast.
        - Centralized audio information handling which means that web interface development for audio plugins will be a lot easier.
        - Optional Audio Ducking so the bot automatically lowers the volume when it detects people talking in the channel.
        - New volume fading feature so that changes in volume are smooth and not abrupt.
> - Major performance/memory optimizations with new audio interface system:
        - Audio threads are created from the audio interface library and will prevent memory leaks and frozen audio
> - Major media plugin improvements (youtube plugin has been renamed to media plugin)
        - SoundCloud URL support (no playlists yet)
        - Youtube playlists generation won't take forever to load (and no audio breaks when generating)
        - Faster youtube searching and video loading
        - Improved thumbnail image retrieval and management
> - Major sound board plugin improvements
        - Support for queuing sound board clips (optional feature, default behaviour is still the same as v3)
        - New commands: `!sbnow/!sbquiet/!sbquietnow/!sbrandomnow/etc etc` (What these commands do will be explained later)
        - Updated sound_board plugin to use any vlc-supported file type.
        - Updated !sbdownload command to download youtube videos as 'webm' file types to save 50x-100x storage space.
        - Added !sbsearch command that uses fuzzy-searching techniques to find files most closely matching the search query.
> - LOTS OF BUG FIXES (way too many to explain)
> - New dependencies:
       - fuzzywuzzy (fuzzy-searching library)
       - python-Levenshtein (increases fuzzy-searching performance up to 10x)
> - Removed dependencies:
       - psutil
